# Generated by Django 3.2 on 2021-05-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commndata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecategory',
            name='delete_flag',
        ),
        migrations.RemoveField(
            model_name='codemaster',
            name='delete_flag',
        ),
    ]
